### PR TITLE
Only include swift files in sources.

### PR DESCRIPTION
**Pull request by kaomte**
This fixes the 'Unexpected duplicate tasks' by including the image files only in the
bundle.

### Pull requests

The easiest way to start contributing is searching open issues by `help wanted` tag. 

* Add test coverage to the feature or fix if you can. We are more likely to accept new feature pull requests that have related test coverage. This allows us to keep the library stable as we move forward.
* Remember to document the new feature. We do not accept new feature pull requests without its associated documentation.
* In case of a new feature please update the example project showing the feature.
* Please only one fix or feature per pull request. This will increase the chances your feature will be merged.

### CODE REVIEW

**Comment by pwnstarSmithy** [comment]
@pavankataria @kaomte when do you intend to merge this? it's a major issue.

**Comment by dkawashima** [comment]
@pavankataria @kaomte How do you use this with CocoaPods? I'm still getting the previous issue as the CocoaPod build has yet to be updated. For Xcode 12, this is a blocker for app release. Is there a way around the CocoaPod build to use something else to get this working. cc @pwnstarSmithy

**Comment by pavankataria** [comment]
@dkawashima @kaomte @pwnstarSmithy 
image

Please upgrade to the latest version of `SwiftDataTables` (0.8.2) to receive a fix for this issue. Thank you. 

 🚀  SwiftDataTables (0.8.2) successfully published on  📅  December 8th, 04:03
👍 Share with your friends and colleagues!

**Comment by dkawashima** [comment]
Thank you! updated

**Pull request merged**
